### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by spectrumcomputing** [markdryan/specasm#7]
Hi Mark,

Sent this is September via the SC forums, but you don't seem to have logged in for a while.

How are you doing?

I have had a proper play with Specasm today, and I'm really impressed. My assembly language skills are low level, but I do produce short routines.

Could I make a few suggestions:

On the GitHub page under 'Assembling Your First Program', there was the following:

`.mkdir /asm/demo`
This did not work for me. I had to do .mkdir /asm, then .mkdir /asm/demo

On some assemblers I can do something like LD A,"D". With Specasm I have to do LD A,68. Any chance of implementing such a feature? It's not a major issue, just a nice to have.

Finally, is there any way you could automate the 'CLEAR 32767: LOAD * "program" CODE 32768: RANDOMIZE USR 32768? Maybe a command like .run program or similar? This is the biggest thing for me!

Keep up the great work.

Peter

**Comment by markdryan** [comment]
> On the GitHub page under 'Assembling Your First Program', there was the following:
> 
> `.mkdir /asm/demo` This did not work for me. I had to do .mkdir /asm, then .mkdir /asm/demo
> 

Thanks.  I'll fix this.

> On some assemblers I can do something like LD A,"D". With Specasm I have to do LD A,68. Any chance of implementing such a feature? It's not a major issue, just a nice to have.

This is currently possible but you need to use single quotes rather than double quotes, so

```
    ld a, 'D'
```

The different number formats accepted by Specasm are documented [here](https://github.com/markdryan/specasm/blob/main/docs/specasm.md#numbers).

> Finally, is there any way you could automate the 'CLEAR 32767: LOAD * "program" CODE 32768: RANDOMIZE USR 32768? Maybe a command like .run program or similar? This is the biggest thing for me!

Agree, this is irritating especially when you're just writing a small program to test things out.  It should be fairly easy to modify the linker to generate a BASIC loader program on request.  You'd then just need to do something like LOAD * "loader".  I'll include this feature in the next release, which should be before the end of the year to coincide with the release of the Next.

**Comment by spectrumcomputing** [comment]
Thanks Mark.  Sounds like  a plan!
